server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:

        # Auth Service
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        # User Service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        # Policy Service
        - id: policy-service
          uri: lb://POLICY-SERVICE
          predicates:
            - Path=/policy/**

        # Claim Service
        - id: claim-service
          uri: lb://CLAIM-SERVICE
          predicates:
            - Path=/claim/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/